package com.limi88.financialplanner.greendao.dao;

import android.database.sqlite.SQLiteDatabase;

import com.limi88.financialplanner.greendao.bean.AccountBean;
import com.limi88.financialplanner.greendao.bean.Search;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig accountBeanDaoConfig;
    private final DaoConfig searchDaoConfig;

    private final AccountBeanDao accountBeanDao;
    private final SearchDao searchDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        accountBeanDaoConfig = daoConfigMap.get(AccountBeanDao.class).clone();
        accountBeanDaoConfig.initIdentityScope(type);

        searchDaoConfig = daoConfigMap.get(SearchDao.class).clone();
        searchDaoConfig.initIdentityScope(type);

        accountBeanDao = new AccountBeanDao(accountBeanDaoConfig, this);
        searchDao = new SearchDao(searchDaoConfig, this);

        registerDao(AccountBean.class, accountBeanDao);
        registerDao(Search.class, searchDao);
    }
    
    public void clear() {
        accountBeanDaoConfig.getIdentityScope().clear();
        searchDaoConfig.getIdentityScope().clear();
    }

    public AccountBeanDao getAccountBeanDao() {
        return accountBeanDao;
    }

    public SearchDao getSearchDao() {
        return searchDao;
    }

}
